### PR TITLE
Add puppet-lint-top_scope_facts-check

### PR DESCRIPTION
**Pull request by bastelfreak**
I did some tests on our modules and didn't notice any false positives.
https://github.com/mmckinst maintains two plugins. We already use their
awesome puppet-lint-legacy_facts-check plugin.
puppet-lint-top_scope_facts-check is a good addition to it. This points
out facts being accessed via top scope like `${::kernel}`. Most of the
occurrences can also be autofixed.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
My selfish concern with this is https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/plugin/remote_execution/ssh_user/params.pp where they certainly aren't facts. That probably needs control statements. Other than that I'm ok with this.

**Comment by bastelfreak** [comment]
I gave it a try on theforeman_proxy and only line 17 in params.pp is detected by this plugin:

```
bastelfreak@bastelfreak-ws ~/puppet-git/foreman_proxy $ git diff
diff --git a/Gemfile b/Gemfile
index 1b20df2..08f00c4 100644
--- a/Gemfile
+++ b/Gemfile
@@ -13,6 +13,7 @@ gem 'puppet-lint-param-docs', '>= 1.3.0', {"groups"=>["test"]}
 gem 'puppet-lint-spaceship_operator_without_tag-check', {"groups"=>["test"]}
 gem 'puppet-lint-strict_indent-check', {"groups"=>["test"]}
 gem 'puppet-lint-undef_in_function-check', {"groups"=>["test"]}
+gem 'puppet-lint-top_scope_facts-check'
 gem 'voxpupuli-test', '~> 1.4', {"groups"=>["test"]}
 gem 'github_changelog_generator', '>= 1.15.0', {"groups"=>["development"]}
 gem 'puppet_metadata', '~> 0.3'
bastelfreak@bastelfreak-ws ~/puppet-git/foreman_proxy $ bundle exec rake lint
manifests/plugin/remote_execution/ssh_user/params.pp:17:top_scope_facts:WARNING:top scope fact instead of facts hash
bastelfreak@bastelfreak-ws ~/puppet-git/foreman_proxy $
```

and that single one is easy to be excluded with a control comment

**Comment by ekohl** [comment]
If it's just one, we can also fool it with `getvar()`

**Review by ekohl — APPROVED** [review]

**Comment by bastelfreak** [comment]
we had some discussion on IRC.  this change will mark existing code, that was previously okay, as bad. Hence we will do a 2.0.0 release and not 1.1.0

**Pull request merged**
